name: Build and Push API & Web to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build dify-api
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dify-api:latest ./api

      - name: Build dify-web
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/dify-web:latest ./web

      - name: Push dify-api
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dify-api:latest

      - name: Push dify-web
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/dify-web:latest
